// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `system_font_database`, `to_usvg_options`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SvgTree>>
abstract class SvgTree implements RustOpaqueInterface {
  /// Returns whether the normalized tree contains no renderable nodes.
  bool get isEmpty;

  /// Parses SVG text into a normalized tree.
  static SvgTree parse({required String svg, ParseOptions? options}) =>
      UsvgRustLibGenerated.instance.api.crateApiSvgTreeParse(
        svg: svg,
        options: options,
      );

  /// Parses SVG bytes into a normalized tree.
  static SvgTree parseBytes({required List<int> data, ParseOptions? options}) =>
      UsvgRustLibGenerated.instance.api.crateApiSvgTreeParseBytes(
        data: data,
        options: options,
      );

  /// Returns the intrinsic size of the root SVG.
  SvgSize get size;

  /// Serializes the normalized tree as SVG text.
  ///
  /// When enabled, successfully parsed text is serialized as text elements
  /// instead of paths. Fonts are still required while parsing.
  String toSvgString({bool preserveText = false});
}

/// Options controlling how usvg parses and resolves an SVG document.
class ParseOptions {
  /// Directory used to resolve relative resource paths.
  final String? resourcesDir;

  /// Resolution used to convert physical units into pixels.
  final double dpi;

  /// Default font family used when an SVG does not specify one.
  final String fontFamily;

  /// Default font size used when an SVG does not specify one.
  final double fontSize;

  /// Preferred languages used to resolve conditional SVG content.
  final List<String> languages;

  /// Additional CSS applied while parsing the SVG.
  final String? styleSheet;

  /// Whether to load fonts installed on the host operating system.
  final bool loadSystemFonts;

  /// Font files to load into usvg's in-memory font database.
  final List<Uint8List> fontData;

  const ParseOptions({
    this.resourcesDir,
    required this.dpi,
    required this.fontFamily,
    required this.fontSize,
    required this.languages,
    this.styleSheet,
    required this.loadSystemFonts,
    required this.fontData,
  });

  static ParseOptions default_() =>
      UsvgRustLibGenerated.instance.api.crateApiParseOptionsDefault();

  @override
  int get hashCode =>
      resourcesDir.hashCode ^
      dpi.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode ^
      languages.hashCode ^
      styleSheet.hashCode ^
      loadSystemFonts.hashCode ^
      fontData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseOptions &&
          runtimeType == other.runtimeType &&
          resourcesDir == other.resourcesDir &&
          dpi == other.dpi &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          languages == other.languages &&
          styleSheet == other.styleSheet &&
          loadSystemFonts == other.loadSystemFonts &&
          fontData == other.fontData;
}

/// The intrinsic dimensions of a parsed SVG tree.
class SvgSize {
  /// Width in SVG user units.
  final double width;

  /// Height in SVG user units.
  final double height;

  const SvgSize({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
