// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_usvg_options`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SvgTree>>
abstract class SvgTree implements RustOpaqueInterface {
  bool get isEmpty;

  static Future<SvgTree> parse({required String svg, ParseOptions? options}) =>
      UsvgRustLibGenerated.instance.api.crateApiSvgTreeParse(
        svg: svg,
        options: options,
      );

  static Future<SvgTree> parseBytes({
    required List<int> data,
    ParseOptions? options,
  }) => UsvgRustLibGenerated.instance.api.crateApiSvgTreeParseBytes(
    data: data,
    options: options,
  );

  SvgSize get size;

  Future<String> toSvgString();
}

class ParseOptions {
  final String? resourcesDir;
  final double dpi;
  final String fontFamily;
  final double fontSize;
  final List<String> languages;
  final String? styleSheet;

  const ParseOptions({
    this.resourcesDir,
    required this.dpi,
    required this.fontFamily,
    required this.fontSize,
    required this.languages,
    this.styleSheet,
  });

  static Future<ParseOptions> default_() =>
      UsvgRustLibGenerated.instance.api.crateApiParseOptionsDefault();

  @override
  int get hashCode =>
      resourcesDir.hashCode ^
      dpi.hashCode ^
      fontFamily.hashCode ^
      fontSize.hashCode ^
      languages.hashCode ^
      styleSheet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseOptions &&
          runtimeType == other.runtimeType &&
          resourcesDir == other.resourcesDir &&
          dpi == other.dpi &&
          fontFamily == other.fontFamily &&
          fontSize == other.fontSize &&
          languages == other.languages &&
          styleSheet == other.styleSheet;
}

class SvgSize {
  final double width;
  final double height;

  const SvgSize({required this.width, required this.height});

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SvgSize &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
