// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class UsvgRustLibGenerated
    extends
        BaseEntrypoint<
          UsvgRustLibGeneratedApi,
          UsvgRustLibGeneratedApiImpl,
          UsvgRustLibGeneratedWire
        > {
  @internal
  static final instance = UsvgRustLibGenerated._();

  UsvgRustLibGenerated._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    UsvgRustLibGeneratedApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required UsvgRustLibGeneratedApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<UsvgRustLibGeneratedApiImpl, UsvgRustLibGeneratedWire>
  get apiImplConstructor => UsvgRustLibGeneratedApiImpl.new;

  @override
  WireConstructor<UsvgRustLibGeneratedWire> get wireConstructor =>
      UsvgRustLibGeneratedWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -929826770;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'usvg_dart_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class UsvgRustLibGeneratedApi extends BaseApi {
  bool crateApiSvgTreeIsEmpty({required SvgTree that});

  SvgTree crateApiSvgTreeParse({required String svg, ParseOptions? options});

  SvgTree crateApiSvgTreeParseBytes({
    required List<int> data,
    ParseOptions? options,
  });

  SvgSize crateApiSvgTreeSize({required SvgTree that});

  String crateApiSvgTreeToSvgString({required SvgTree that});

  ParseOptions crateApiParseOptionsDefault();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_SvgTree;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_SvgTree;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SvgTreePtr;
}

class UsvgRustLibGeneratedApiImpl extends UsvgRustLibGeneratedApiImplPlatform
    implements UsvgRustLibGeneratedApi {
  UsvgRustLibGeneratedApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiSvgTreeIsEmpty({required SvgTree that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSvgTreeIsEmptyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgTreeIsEmptyConstMeta =>
      const TaskConstMeta(debugName: "SvgTree_is_empty", argNames: ["that"]);

  @override
  SvgTree crateApiSvgTreeParse({required String svg, ParseOptions? options}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(svg, serializer);
          sse_encode_opt_box_autoadd_parse_options(options, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSvgTreeParseConstMeta,
        argValues: [svg, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgTreeParseConstMeta => const TaskConstMeta(
    debugName: "SvgTree_parse",
    argNames: ["svg", "options"],
  );

  @override
  SvgTree crateApiSvgTreeParseBytes({
    required List<int> data,
    ParseOptions? options,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_opt_box_autoadd_parse_options(options, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSvgTreeParseBytesConstMeta,
        argValues: [data, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgTreeParseBytesConstMeta => const TaskConstMeta(
    debugName: "SvgTree_parse_bytes",
    argNames: ["data", "options"],
  );

  @override
  SvgSize crateApiSvgTreeSize({required SvgTree that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_svg_size,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSvgTreeSizeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgTreeSizeConstMeta =>
      const TaskConstMeta(debugName: "SvgTree_size", argNames: ["that"]);

  @override
  String crateApiSvgTreeToSvgString({required SvgTree that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSvgTreeToSvgStringConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSvgTreeToSvgStringConstMeta => const TaskConstMeta(
    debugName: "SvgTree_to_svg_string",
    argNames: ["that"],
  );

  @override
  ParseOptions crateApiParseOptionsDefault() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parse_options,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiParseOptionsDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiParseOptionsDefaultConstMeta =>
      const TaskConstMeta(debugName: "parse_options_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SvgTree => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SvgTree => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree;

  @protected
  SvgTree
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SvgTreeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SvgTree
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SvgTreeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SvgTree
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SvgTreeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ParseOptions dco_decode_box_autoadd_parse_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_parse_options(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ParseOptions? dco_decode_opt_box_autoadd_parse_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_parse_options(raw);
  }

  @protected
  ParseOptions dco_decode_parse_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ParseOptions(
      resourcesDir: dco_decode_opt_String(arr[0]),
      dpi: dco_decode_f_32(arr[1]),
      fontFamily: dco_decode_String(arr[2]),
      fontSize: dco_decode_f_32(arr[3]),
      languages: dco_decode_list_String(arr[4]),
      styleSheet: dco_decode_opt_String(arr[5]),
      loadSystemFonts: dco_decode_bool(arr[6]),
      fontData: dco_decode_list_list_prim_u_8_strict(arr[7]),
    );
  }

  @protected
  SvgSize dco_decode_svg_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SvgSize(
      width: dco_decode_f_32(arr[0]),
      height: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  SvgTree
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SvgTreeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SvgTree
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SvgTreeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SvgTree
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SvgTreeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ParseOptions sse_decode_box_autoadd_parse_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_parse_options(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseOptions? sse_decode_opt_box_autoadd_parse_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_parse_options(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseOptions sse_decode_parse_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_resourcesDir = sse_decode_opt_String(deserializer);
    var var_dpi = sse_decode_f_32(deserializer);
    var var_fontFamily = sse_decode_String(deserializer);
    var var_fontSize = sse_decode_f_32(deserializer);
    var var_languages = sse_decode_list_String(deserializer);
    var var_styleSheet = sse_decode_opt_String(deserializer);
    var var_loadSystemFonts = sse_decode_bool(deserializer);
    var var_fontData = sse_decode_list_list_prim_u_8_strict(deserializer);
    return ParseOptions(
      resourcesDir: var_resourcesDir,
      dpi: var_dpi,
      fontFamily: var_fontFamily,
      fontSize: var_fontSize,
      languages: var_languages,
      styleSheet: var_styleSheet,
      loadSystemFonts: var_loadSystemFonts,
      fontData: var_fontData,
    );
  }

  @protected
  SvgSize sse_decode_svg_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_f_32(deserializer);
    var var_height = sse_decode_f_32(deserializer);
    return SvgSize(width: var_width, height: var_height);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    SvgTree self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SvgTreeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    SvgTree self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SvgTreeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSvgTree(
    SvgTree self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SvgTreeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_parse_options(
    ParseOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_parse_options(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_parse_options(
    ParseOptions? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_parse_options(self, serializer);
    }
  }

  @protected
  void sse_encode_parse_options(ParseOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.resourcesDir, serializer);
    sse_encode_f_32(self.dpi, serializer);
    sse_encode_String(self.fontFamily, serializer);
    sse_encode_f_32(self.fontSize, serializer);
    sse_encode_list_String(self.languages, serializer);
    sse_encode_opt_String(self.styleSheet, serializer);
    sse_encode_bool(self.loadSystemFonts, serializer);
    sse_encode_list_list_prim_u_8_strict(self.fontData, serializer);
  }

  @protected
  void sse_encode_svg_size(SvgSize self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.width, serializer);
    sse_encode_f_32(self.height, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class SvgTreeImpl extends RustOpaque implements SvgTree {
  // Not to be used by end users
  SvgTreeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SvgTreeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: UsvgRustLibGenerated
        .instance
        .api
        .rust_arc_increment_strong_count_SvgTree,
    rustArcDecrementStrongCount: UsvgRustLibGenerated
        .instance
        .api
        .rust_arc_decrement_strong_count_SvgTree,
    rustArcDecrementStrongCountPtr: UsvgRustLibGenerated
        .instance
        .api
        .rust_arc_decrement_strong_count_SvgTreePtr,
  );

  /// Returns whether the normalized tree contains no renderable nodes.
  bool get isEmpty =>
      UsvgRustLibGenerated.instance.api.crateApiSvgTreeIsEmpty(that: this);

  /// Returns the intrinsic size of the root SVG.
  SvgSize get size =>
      UsvgRustLibGenerated.instance.api.crateApiSvgTreeSize(that: this);

  /// Serializes the normalized tree as SVG text.
  String toSvgString() =>
      UsvgRustLibGenerated.instance.api.crateApiSvgTreeToSvgString(that: this);
}
