import 'dart:convert';
import 'dart:io';

const _chunkLength = 80;

void main() {
  final javascript = File('web/pkg/usvg_dart_rust.js').readAsBytesSync();
  final wasm = File('web/pkg/usvg_dart_rust_bg.wasm').readAsBytesSync();
  final output = File('lib/src/web_wasm_assets.dart');

  output.writeAsStringSync('''
// Generated by scripts/generate_web_wasm_assets.dart. Do not edit.

const embeddedWasmBindgenJavaScriptBase64 =
${_dartString(base64Encode(javascript))};

const embeddedWasmBinaryBase64 =
${_dartString(base64Encode(wasm))};
''');
}

String _dartString(String value) {
  final chunks = <String>[
    for (var offset = 0; offset < value.length; offset += _chunkLength)
      value.substring(
        offset,
        offset + _chunkLength > value.length
            ? value.length
            : offset + _chunkLength,
      ),
  ];
  return chunks.map((chunk) => "    '$chunk'").join('\n');
}
